In [15]:
# ==========================================
# Customer Shopping Behavior Analysis
# ==========================================

import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus
from IPython.display import display

# Load Dataset
df = pd.read_csv("customer_shopping_behavior.csv")

print("========== FIRST 5 ROWS ==========")
display(df.head())

print("\n========== DATASET INFORMATION ==========")
df.info()

print("\n========== SUMMARY STATISTICS ==========")
display(df.describe())

print("\n========== MISSING VALUES ==========")
display(df.isnull().sum())

print("\n========== FILLING MISSING VALUES ==========")

df["Review Rating"] = (
    df.groupby("Category")["Review Rating"]
      .transform(lambda x: x.fillna(x.median()))
)

print("Remaining Missing Values:")
display(df["Review Rating"].isnull().sum())

print("\n========== STANDARDIZING COLUMN NAMES ==========")

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_")
df.rename(columns={"purchase_amount_(usd)": "purchase_amount"}, inplace=True)

display(df.columns)

print("\n========== CREATING AGE GROUPS ==========")

labels = ["Young Adult", "Adult", "Middle-aged", "Senior"]

df["age_group"] = pd.qcut(
    df["age"],
    q=4,
    labels=labels
)

display(df[["age", "age_group"]].head())

print("\n========== PURCHASE FREQUENCY MAPPING ==========")

frequency_mapping = {
    "Weekly": 52,
    "Bi-Weekly": 26,
    "Fortnightly": 26,
    "Monthly": 12,
    "Quarterly": 4,
    "Every 3 Months": 4,
    "Annually": 1
}

df["frequency_per_year"] = df["frequency_of_purchases"].map(frequency_mapping)

display(df[["frequency_of_purchases", "frequency_per_year"]].head())

print("\n========== CONNECTING TO POSTGRESQL ==========")

username = "postgres"
password = quote_plus("Tanu@1107")
host = "localhost"
port = "5432"
database = "customer_behaviour"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

print("Database Connected Successfully!")

print("\n========== EXPORTING DATA TO POSTGRESQL ==========")

df.to_sql(
    "customer_behaviour",
    engine,
    if_exists="replace",
    index=False
)

print("Data Exported Successfully!")

print("\n========== FINAL DATASET ==========")
display(df.head())

========== FIRST 5 ROWS ==========

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

========== DATASET INFORMATION ==========
<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

========== SUMMARY STATISTICS ==========

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

========== MISSING VALUES ==========

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

========== FILLING MISSING VALUES ==========
Remaining Missing Values:

np.int64(0)

========== STANDARDIZING COLUMN NAMES ==========

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

========== CREATING AGE GROUPS ==========

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged

========== PURCHASE FREQUENCY MAPPING ==========

  frequency_of_purchases  frequency_per_year
0            Fortnightly                  26
1            Fortnightly                  26
2                 Weekly                  52
3                 Weekly                  52
4               Annually                   1

========== CONNECTING TO POSTGRESQL ==========
Database Connected Successfully!

========== EXPORTING DATA TO POSTGRESQL ==========
Data Exported Successfully!

========== FINAL DATASET ==========

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group,frequency_per_year
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,Middle-aged,26
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,Young Adult,26
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Middle-aged,52
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,Young Adult,52
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,Middle-aged,1